version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - MIGRATIONS_DIRECTORY=${MIGRATIONS_DIRECTORY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - /tmp/banner_rotation/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  server:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - MIGRATIONS_DIRECTORY=${MIGRATIONS_DIRECTORY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: .
    restart: always
    depends_on:
      - "postgres"
      - "rabbit"
    volumes:
      - ./logs:/logs
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "postgres"
      - "rabbit"
    ports:
      - "8088:8088"