version: "3.9"
services:
  server:
    build: .
    depends_on:
      - "postgres"
      - "rabbit"
    volumes:
      - ./logs:/logs
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "postgres"
      - "rabbit"
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"